function avg_pod_std = DatPFC_PulseTiming_HeightTiming_Converted_FindPeakStd(chch,pstart,pend)  
    npods = 0;
    avg_pod_std = 0;
    for pp = 1:length(chch.pod_start_samples)
        pod_start = chch.pod_start_samples(pp);
        pod_end = pod_start + chch.pod_length_samples(pp) -1;
        if (pod_start > pend) || (pod_end < pstart)
            continue
        end
        pod_data = chch.pod_data_phe_per_sample(... 
        (chch.pod_start_samples(pp) <= chch.pod_time_samples)...
        &...
        (chch.pod_time_samples <= (chch.pod_start_samples(pp)+chch.pod_length_samples(pp)-1))...
        );
        avg_pod_std = avg_pod_std + max(...
            sum(pod_data( (0:23)+1 ).*pod_data( (0:23)+1 )./24)...
            ,...
            sum(pod_data( ((pod_end-pod_start):-1:(pod_end-pod_start - 31 + 1))+1 ).*pod_data( ((pod_end-pod_start):-1:(pod_end-pod_start - 31 + 1))+1 )./31)...
            );
        npods = npods + 1;
    end
    if npods > 0
        avg_pod_std = sqrt(avg_pod_std/npods);
    end
end
